openapi: 3.0.0
info:
  title: Wallet API
  version: '1.0'
servers:
  - url: 'http://localhost:8080'
paths:
  '/wallets/{user_id}':
    parameters:
      - schema:
          type: string
        name: user_id
        in: path
        required: true
        examples:
          GET_WALLET:
            value: '1'
    get:
      summary: Fetch wallet
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/Wallet'
              examples:
                GET_WALLET:
                  value:
                    id: 1
                    user_id: '1'
                    balance: 3.50
components:
  schemas:
    Wallet:
      title: A user's wallet
      type: object
      properties:
        balance:
          type: string
        id:
          type: number
        user_id:
          type: string
      required:
        - balance
        - id
        - user_id
